server:
  port: 8091
  tomcat:
    uri-encoding: UTF-8

spring:
  config:
    activate:
      on-profile: "test"

  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:h2:mem:accountdb;MODE=MySQL;DB_CLOSE_DELAY=-1
      username: account
      password: account1234

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      schema-locations: classpath:h2db/schema.sql
      data-locations: classpath:h2db/data.sql
      username: account
      password: account1234
      mode: always
      encoding: UTF-8

logging:
  level:
    root: INFO
    com.zaxxer.hikari.pool.HikariPool: INFO
    org:
      springframework:
        boot:
          autoconfigure: ERROR
    jdbc:
      sqlonly: OFF
      sqltiming: INFO
      resultsettable: INFO
      audit: OFF
      resultset: OFF
      connection: OFF