server:
  port: 8090
  servlet:
    context-path: /franc/api
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8

spring:
  output:
    ansi:
      enabled: always

  datasource:
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: franc-pool

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  web:
    resources:
      add-mappings: false

logging:
  config: classpath:log4j2.xml