server:
  port: 8090
  servlet:
    context-path: /franc/api
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8

spring:
  output:
    ansi:
      enabled: always
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  web:
    resources:
      add-mappings: false