INSERT INTO ACCOUNT (ACCOUNT_ID, NAME, STATUS, EMAIL, VIP_YN, INSERT_USER)
    VALUES (1, 'JOHN', 'ON', 'john@naver.com', false, 1);
INSERT INTO ACCOUNT (ACCOUNT_ID, NAME, STATUS, EMAIL, VIP_YN, INSERT_USER)
    VALUES (2, 'MAX', 'ST', 'max@gmail.com', true, 1);
INSERT INTO ACCOUNT (ACCOUNT_ID, NAME, STATUS, EMAIL, VIP_YN, INSERT_USER)
    VALUES (3, 'ROBERT', 'DL', 'robert@naver.com', false, 1);