drop table if exists ACCOUNT;

CREATE TABLE ACCOUNT (
    ACCOUNT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '회원번호',
    NAME VARCHAR(50) NOT NULL COMMENT '회원이름',
    STATUS VARCHAR(2) DEFAULT 'ON' COMMENT '상태 (ON:사용, ST:정지, DL:탈퇴)',
    EMAIL VARCHAR(50) NOT NULL COMMENT '이메일',
    VIP_YN BOOLEAN DEFAULT FALSE COMMENT 'VIP여부',
    INSERT_DATE TIMESTAMP DEFAULT NOW() COMMENT '등록일자',
    INSERT_USER BIGINT COMMENT '등록자ID',
    UPDATE_DATE TIMESTAMP COMMENT '수정일자',
    UPDATE_USER BIGINT COMMENT '수정자ID',
    CONSTRAINT ACCOUNT_PK PRIMARY KEY(ACCOUNT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '회원정보';

